# Generated by Django 5.0 on 2023-12-17 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nome",
        ),
    ]
